workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - ios_credentials
      vars:
        BUNDLE_ID: com.calebroberson.householdapp
        XCODE_WORKSPACE: ios/Runner.xcworkspace
        XCODE_SCHEME: Runner
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files $BUNDLE_ID \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Flutter build iOS
        script: flutter build ios --release --no-codesign
      - name: Package IPA
        script: xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build Android
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
