workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - ios_credentials
      vars:
        BUNDLE_ID: com.calebroberson.householdapp
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files $BUNDLE_ID \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build iOS
        script: |
          cd ios && xcode-project build-ipa \
            --workspace Runner.xcworkspace \
            --scheme Runner \
            --config Release
    artifacts:
      - build/ios/ipa/*.ipa
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build Android
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
